/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sovana.sewa.dialogactivity;

import com.sovana.sewa.connection.Connect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageAdminDialog extends javax.swing.JDialog {

    /**
     * Creates new form ManageAdminDialog
     */
    public ManageAdminDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        load_table_admin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAdmin = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dropdownHakAkses = new javax.swing.JComboBox<>();
        btnSetAccessLevel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namaAdminText = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Admin");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Kelola Admin");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("<html><p style=\"word-wrap: break-word;\">Sebagai pemilik, Anda berhak mengelola hak akses setiap admin untuk aplikasi ini. Anda juga dapat menghapus akun admin dari sistem.</p>");

        tabelAdmin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tabelAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama admin", "Hak akses"
            }
        ));
        tabelAdmin.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelAdmin.setRowHeight(24);
        tabelAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelAdminFocusGained(evt);
            }
        });
        tabelAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelAdminMouseReleased(evt);
            }
        });
        tabelAdmin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabelAdminComponentShown(evt);
            }
        });
        tabelAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelAdminKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAdmin);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Hak akses:");

        dropdownHakAkses.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        dropdownHakAkses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih...", "admin", "pending", "rejected" }));
        dropdownHakAkses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dropdownHakAksesFocusGained(evt);
            }
        });

        btnSetAccessLevel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSetAccessLevel.setText("Simpan");
        btnSetAccessLevel.setFocusPainted(false);
        btnSetAccessLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetAccessLevelActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDelete.setText("Hapus akun ini");
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Username:");

        namaAdminText.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        namaAdminText.setText("Pilih dari tabel...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dropdownHakAkses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(btnSetAccessLevel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnDelete))
                .addComponent(jLabel3)
                .addComponent(namaAdminText))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaAdminText)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropdownHakAkses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetAccessLevel)
                    .addComponent(btnDelete))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        btnDone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDone.setText("Selesai");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(47, 47, 47))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelAdminComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelAdminComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelAdminComponentShown

    private void dropdownHakAksesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dropdownHakAksesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownHakAksesFocusGained

    private void tabelAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelAdminFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelAdminFocusGained

    private void tabelAdminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAdminMouseReleased
        // TODO add your handling code here:
        selectdata();
    }//GEN-LAST:event_tabelAdminMouseReleased

    private void tabelAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelAdminKeyReleased
        // TODO add your handling code here:
        selectdata();
    }//GEN-LAST:event_tabelAdminKeyReleased

    private void btnSetAccessLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetAccessLevelActionPerformed
        // TODO add your handling code here:
        try {
            String sql = String.format("update admin set accesslevel='%s' where username='%s'", dropdownHakAkses.getSelectedItem().toString(), namaAdminText.getText());
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            load_table_admin();
            resetform();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengubah hak akses:\n" + e.getMessage(), "Error", 0);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        }
    }//GEN-LAST:event_btnSetAccessLevelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String sql = String.format("delete from admin where username = '%s'", tabelAdmin.getValueAt(tabelAdmin.getSelectedRow(), 0));
            Connection conn = (Connection) Connect.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            Object[] tombol = {"Hapus", "Batal"};
            int yatidak = JOptionPane.showOptionDialog(null, String.format("Admin '%s' akan dihapus dan tidak dapat digunakan untuk login kembali.%nLanjutkan?", namaAdminText.getText()), "Konfirmasi hapus",
                    0, 2, null, tombol, tombol[1]);
            if (yatidak == JOptionPane.NO_OPTION) {
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            } else if (yatidak == JOptionPane.YES_OPTION) {
                ps.execute();
                load_table_admin();
                resetform();
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data:\n" + e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void selectdata(){
        int baris = tabelAdmin.getSelectedRow();
        namaAdminText.setText(tabelAdmin.getValueAt(baris, 0).toString());
        dropdownHakAkses.setSelectedItem(tabelAdmin.getValueAt(baris, 1));
    }
    
    private void resetform(){
        namaAdminText.setText("Pilih dari tabel...");
        dropdownHakAkses.setSelectedIndex(0);
    }
    
    private void load_table_admin() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("USERNAME");
        model.addColumn("HAK AKSES");
        //menampilkan data database kedalam tabel
        try {
            String sql = "SELECT username, accesslevel FROM `admin` WHERE accesslevel NOT IN ('owner')";
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2)
                });
            }
            tabelAdmin.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ManageAdminDialog dialog = new ManageAdminDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnSetAccessLevel;
    private javax.swing.JComboBox<String> dropdownHakAkses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaAdminText;
    private javax.swing.JTable tabelAdmin;
    // End of variables declaration//GEN-END:variables
}
