/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sovana.sewa.dialogactivity;

import java.sql.Connection;
import java.sql.PreparedStatement;
import com.sovana.sewa.connection.Connect;
import com.sovana.sewa.mainactivity.Main;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class tambahBarangDialog extends javax.swing.JDialog {

    /**
     * Creates new form tambahSewaDialog
     */
    public tambahBarangDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSewaMain = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        idTextBarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namaTextBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        statusBarang = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        hargaText = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah sewaan baru");
        getContentPane().setLayout(new java.awt.CardLayout());

        addSewaMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Tambah barang baru");
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        idTextBarang.setEditable(false);
        idTextBarang.setPreferredSize(new java.awt.Dimension(105, 24));

        jLabel12.setText("ID barang");
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel13.setText("Nama barang");
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel14.setText("Status");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton9.setText("Batal");
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        statusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBarangActionPerformed(evt);
            }
        });

        jLabel15.setText("Harga (Rp)");
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        hargaText.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));

        javax.swing.GroupLayout addSewaMainLayout = new javax.swing.GroupLayout(addSewaMain);
        addSewaMain.setLayout(addSewaMainLayout);
        addSewaMainLayout.setHorizontalGroup(
            addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSewaMainLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addSewaMainLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addGroup(addSewaMainLayout.createSequentialGroup()
                        .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaTextBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addSewaMainLayout.setVerticalGroup(
            addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSewaMainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaTextBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(hargaText))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(addSewaMain, "addSewaMain");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void populateStatusItem() {
        statusBarang.addItem("Tersedia");
        statusBarang.addItem("Habis");
    }

    public void lastIdBarang() {
        try {
            String sql = "select max(id) from barang";
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                int nomer = res.getInt("max(id)") + 1;
                idTextBarang.setText(Integer.toString(nomer));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }

    public void addMode() {
        setTitle("Tambah barang baru");
        jLabel10.setText("Tambah barang baru");
        btnTambah.setText("Tambah");
        populateStatusItem();
        lastIdBarang();
    }

    public void editMode(String id_number) {
        setTitle("Edit barang");
        jLabel10.setText("Edit barang");
        btnTambah.setText("Simpan");
        populateStatusItem();
        try {
            String sql = "select*from barang where id = " + id_number + "";
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                idTextBarang.setText(res.getString(1));
                namaTextBarang.setText(res.getString(2));
                hargaText.setValue(Integer.parseInt(res.getString(3)));
                statusBarang.setSelectedItem(res.getString(4));
            }
        } catch (SQLException e) {
            e.getMessage();
        }

    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (jLabel10.getText().equals("Tambah barang baru")) {
            try {
                String sql = "INSERT INTO barang (nama_barang, harga, status) VALUES "
                        + "('" + namaTextBarang.getText() + "','"
                        + hargaText.getValue().toString() + "','"
                        + statusBarang.getSelectedItem().toString() + "')";
                Connection conn = (Connection) Connect.configDB();
                PreparedStatement pst = conn.prepareStatement(sql);
                conn.prepareStatement("ALTER TABLE barang AUTO_INCREMENT=0").execute();
                pst.execute();
                ((Main) getOwner()).load_table_barang();
                ((Main) getOwner()).showSummaryCount();
                dispose();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan:\n" + e.getMessage(), "Error", 0);
            }

        } else if (jLabel10.getText().equals("Edit barang")) {
            try {
                String sql = "UPDATE barang SET nama_barang = '" + namaTextBarang.getText() + "',"
                        + " harga = '" + hargaText.getValue().toString() + "',"
                        + " status = '" + statusBarang.getSelectedItem().toString() + "'"
                        + " WHERE id = '" + idTextBarang.getText() + "'";
                Connection conn = (Connection) Connect.configDB();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                ((Main) getOwner()).load_table_barang();
                ((Main) getOwner()).showSummaryCount();
                dispose();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal diedit:\n" + e.getMessage(), "Error", 0);
            }

        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void statusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahBarangDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tambahBarangDialog dialog = new tambahBarangDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addSewaMain;
    private javax.swing.JButton btnTambah;
    private javax.swing.JSpinner hargaText;
    private javax.swing.JTextField idTextBarang;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaTextBarang;
    private javax.swing.JComboBox<String> statusBarang;
    // End of variables declaration//GEN-END:variables
}
