/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sovana.sewa.dialogactivity;

import java.sql.Connection;
import java.sql.PreparedStatement;
import com.sovana.sewa.connection.Connect;
import com.sovana.sewa.mainactivity.Main;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Locale;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class tambahSewaDialog extends javax.swing.JDialog {

    /**
     * Creates new form tambahSewaDialog
     */
    public tambahSewaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    SimpleDateFormat formatter = new SimpleDateFormat("dd MMM yyyy");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSewaMain = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        idTextSewa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        namaTextSewa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamatTextSewa = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        telpTextSewa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        barangTextSewa = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jumlahBarangSewa = new javax.swing.JSpinner();
        tglSewa = new com.github.lgooddatepicker.components.DatePicker();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah sewaan baru");
        getContentPane().setLayout(new java.awt.CardLayout());

        addSewaMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Tambah sewaan baru");
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        idTextSewa.setEditable(false);
        idTextSewa.setPreferredSize(new java.awt.Dimension(105, 24));

        jLabel12.setText("ID sewaan");
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel13.setText("Nama penyewa");
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel14.setText("Barang yang disewa");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel19.setText("Alamat penyewa");
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        alamatTextSewa.setColumns(20);
        alamatTextSewa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        alamatTextSewa.setRows(5);
        alamatTextSewa.setWrapStyleWord(true);
        jScrollPane3.setViewportView(alamatTextSewa);

        jLabel20.setText("No. telp");
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jButton9.setText("Batal");
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        barangTextSewa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih..." }));

        jLabel21.setText("Jumlah");
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        tglSewa.setDate(LocalDate.of(1970, 01, 01)
        );
        tglSewa.setBackground(new java.awt.Color(255, 255, 255));
        tglSewa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tglSewa.setPreferredSize(new java.awt.Dimension(144, 25));
        tglSewa.setSettings(null);
        tglSewa.setToolTipText("");
        tglSewa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tglSewaFocusGained(evt);
            }
        });
        tglSewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tglSewaMouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel15.setText("Tanggal sewa");

        tglSewa.getComponentToggleCalendarButton().setIcon(new ImageIcon(getClass().getResource("/com/sovana/sewa/images/Calendar-icon.png")));
        tglSewa.getComponentToggleCalendarButton().setText("");
        tglSewa.setLocale(new Locale("id", "ID"));

        javax.swing.GroupLayout addSewaMainLayout = new javax.swing.GroupLayout(addSewaMain);
        addSewaMain.setLayout(addSewaMainLayout);
        addSewaMainLayout.setHorizontalGroup(
            addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSewaMainLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addSewaMainLayout.createSequentialGroup()
                        .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addSewaMainLayout.createSequentialGroup()
                                .addComponent(barangTextSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahBarangSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(55, Short.MAX_VALUE))
                            .addGroup(addSewaMainLayout.createSequentialGroup()
                                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                    .addComponent(telpTextSewa))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(addSewaMainLayout.createSequentialGroup()
                        .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(addSewaMainLayout.createSequentialGroup()
                                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTextSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaTextSewa, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(tglSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(59, 59, 59))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addSewaMainLayout.setVerticalGroup(
            addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSewaMainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaTextSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(barangTextSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21)
                    .addComponent(jumlahBarangSewa))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addSewaMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telpTextSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(addSewaMain, "addSewaMain");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void populateBarangItem() {
        try {
            String sql = "select nama_barang from barang";
            Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[1];
                o[0] = res.getString(1);
                barangTextSewa.addItem((String) o[0]);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }

    public void lastIdSewaan() {
        try {
            String sql = "select max(id) from sewaan";
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                int nomer = res.getInt("max(id)") + 1;
                idTextSewa.setText(Integer.toString(nomer));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }

    public void addMode() {
        setTitle("Tambah sewaan baru");
        jLabel10.setText("Tambah sewaan baru");
        btnTambah.setText("Tambah");
        populateBarangItem();
        lastIdSewaan();
    }

    public void editMode(String id_number) {
        setTitle("Edit sewaan");
        jLabel10.setText("Edit sewaan");
        btnTambah.setText("Simpan");
        populateBarangItem();
        try {
            String sql = "select*from sewaan where id = " + id_number + "";
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                idTextSewa.setText(res.getString(1));
                tglSewa.setDate(res.getDate(2).toLocalDate());
                namaTextSewa.setText(res.getString(3));
                barangTextSewa.setSelectedItem(res.getString(4));
                jumlahBarangSewa.setValue(Integer.parseInt(res.getString(5)));
                alamatTextSewa.setText(res.getString(6));
                telpTextSewa.setText(res.getString(7));
            }
        } catch (SQLException e) {
            e.getMessage();
        }

    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (jLabel10.getText().equals("Tambah sewaan baru")) {
            try {
                String sql = "INSERT INTO sewaan (tanggal,nama,barang_sewaan,jumlah,alamat,telp) VALUES "
                        + "('" + tglSewa.getDateStringOrEmptyString()
                        + "','" + namaTextSewa.getText()
                        + "','" + barangTextSewa.getSelectedItem().toString()
                        + "','" + jumlahBarangSewa.getValue().toString()
                        + "','" + alamatTextSewa.getText()
                        + "','" + telpTextSewa.getText() + "')";
                Connection conn = (Connection) Connect.configDB();
                PreparedStatement pst = conn.prepareStatement(sql);
                conn.prepareStatement("ALTER TABLE sewaan AUTO_INCREMENT=0").execute();
                pst.execute();
                ((Main) getOwner()).load_table_sewaan();
                ((Main) getOwner()).showSummaryCount();
                dispose();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Data gagal disimpan:\n" + e.getMessage(), "Error", 0);
            }

        } else if (jLabel10.getText().equals("Edit sewaan")) {
            try {
                String sql = "UPDATE sewaan SET tanggal = '" + tglSewa.getDateStringOrEmptyString() + "', "
                        + "nama = '" + namaTextSewa.getText() + "', "
                        + "barang_sewaan = '" + barangTextSewa.getSelectedItem().toString() + "', "
                        + "jumlah = '" + jumlahBarangSewa.getValue().toString() + "',"
                        + "alamat = '" + alamatTextSewa.getText() + "',"
                        + "telp= '" + telpTextSewa.getText() + "'"
                        + " WHERE id = '" + idTextSewa.getText() + "'";
                Connection conn = (Connection) Connect.configDB();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                ((Main) getOwner()).load_table_sewaan();
                ((Main) getOwner()).showSummaryCount();
                dispose();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal diedit:\n" + e.getMessage(), "Error", 0);
            }

        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tglSewaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglSewaMouseReleased
        
    }//GEN-LAST:event_tglSewaMouseReleased

    private void tglSewaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tglSewaFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tglSewaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahSewaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahSewaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahSewaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahSewaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tambahSewaDialog dialog = new tambahSewaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addSewaMain;
    private javax.swing.JTextArea alamatTextSewa;
    private javax.swing.JComboBox<String> barangTextSewa;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField idTextSewa;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jumlahBarangSewa;
    private javax.swing.JTextField namaTextSewa;
    private javax.swing.JTextField telpTextSewa;
    private com.github.lgooddatepicker.components.DatePicker tglSewa;
    // End of variables declaration//GEN-END:variables
}
