/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sovana.sewa.mainactivity;

import com.sovana.sewa.dialogactivity.tambahBarangDialog;
import com.sovana.sewa.dialogactivity.changePasswordDialog;
import com.sovana.sewa.dialogactivity.tambahSewaDialog;
import com.sovana.sewa.dialogactivity.bayarDialog;
import java.sql.Connection;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import com.sovana.sewa.connection.Session;
import com.sovana.sewa.connection.Connect;
import com.sovana.sewa.dialogactivity.printPreviewDialog;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {

    ResultSet rs;
    PreparedStatement pst;
    SimpleDateFormat formatter = new SimpleDateFormat("dd MMM yyyy");
    String username = Session.getUsername();
    String level = Session.getLevel();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        try {
            Connection conn = (Connection) Connect.configDB();
            String sql = "select * from admin where username = ?";

            PreparedStatement stm = conn.prepareStatement(sql);
            stm.setString(1, username);
            ResultSet res = stm.executeQuery();
            while (res.next()) {
                btnAccount.setText(username + " (" + level + ")");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        showSummaryCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        useroptions = new javax.swing.JPopupMenu();
        menuEditAcc = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        mainpage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        numberSewa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnToSewaan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        numberBarang = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnToBarang = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        numberBlmLunas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnToPayment = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        datasewaan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sewaTambah = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        bayarBtn = new javax.swing.JButton();
        sewaEdit = new javax.swing.JButton();
        sewaHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSewaan = new javax.swing.JTable();
        searchSewa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        databarang = new javax.swing.JPanel();
        searchBarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        barangTambah = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        barangEdit = new javax.swing.JButton();
        barangHapus = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        riwayat = new javax.swing.JPanel();
        searchRiwayat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        riwayatCetak = new javax.swing.JButton();
        riwayatHapus = new javax.swing.JButton();
        riwayatHapusAll = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelRiwayat = new javax.swing.JTable();
        belumLunasCheckbox = new javax.swing.JCheckBox();

        useroptions.setBackground(new java.awt.Color(51, 51, 51));
        useroptions.setForeground(new java.awt.Color(255, 255, 255));
        useroptions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        menuEditAcc.setText("Ubah password");
        menuEditAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditAccActionPerformed(evt);
            }
        });
        useroptions.add(menuEditAcc);

        menuLogout.setText("Log out");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        useroptions.add(menuLogout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SewaTerop");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        mainpage.setBackground(new java.awt.Color(255, 255, 255));
        mainpage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainpage.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                mainpageComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 4));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        numberSewa.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numberSewa.setForeground(new java.awt.Color(51, 51, 51));
        numberSewa.setText("0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Sewaan berlangsung");

        btnToSewaan.setBackground(new java.awt.Color(51, 153, 255));
        btnToSewaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnToSewaan.setForeground(new java.awt.Color(51, 153, 255));
        btnToSewaan.setText("Kelola sewaan");
        btnToSewaan.setBorder(null);
        btnToSewaan.setBorderPainted(false);
        btnToSewaan.setContentAreaFilled(false);
        btnToSewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToSewaan.setFocusPainted(false);
        btnToSewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToSewaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(numberSewa))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnToSewaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numberSewa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnToSewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        numberBarang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numberBarang.setForeground(new java.awt.Color(51, 51, 51));
        numberBarang.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Barang tersedia");

        btnToBarang.setBackground(new java.awt.Color(51, 153, 255));
        btnToBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnToBarang.setForeground(new java.awt.Color(255, 102, 51));
        btnToBarang.setText("Kelola barang");
        btnToBarang.setBorder(null);
        btnToBarang.setBorderPainted(false);
        btnToBarang.setContentAreaFilled(false);
        btnToBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToBarang.setFocusPainted(false);
        btnToBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(numberBarang))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnToBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numberBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnToBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        numberBlmLunas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        numberBlmLunas.setForeground(new java.awt.Color(51, 51, 51));
        numberBlmLunas.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Sewaan belum lunas");

        btnToPayment.setBackground(new java.awt.Color(51, 153, 255));
        btnToPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnToPayment.setForeground(new java.awt.Color(153, 0, 0));
        btnToPayment.setText("Riwayat transaksi");
        btnToPayment.setBorder(null);
        btnToPayment.setBorderPainted(false);
        btnToPayment.setContentAreaFilled(false);
        btnToPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToPayment.setFocusPainted(false);
        btnToPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(numberBlmLunas))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnToPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numberBlmLunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(btnToPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sovana/sewa/images/baseline_assignment_white_24dp.png"))); // NOI18N
        jButton4.setText("Pesanan baru");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setIconTextGap(8);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sovana/sewa/images/baseline_widgets_white_24dp.png"))); // NOI18N
        jButton5.setText("Barang baru");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setIconTextGap(8);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tambahkan");

        btnAccount.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(0, 51, 153));
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sovana/sewa/images/baseline_keyboard_arrow_down_black_18dp.png"))); // NOI18N
        btnAccount.setText("ahmad_billie_elisyah (owner)");
        btnAccount.setBorderPainted(false);
        btnAccount.setComponentPopupMenu(useroptions);
        btnAccount.setContentAreaFilled(false);
        btnAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAccountMouseReleased(evt);
            }
        });
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 255));
        jButton6.setText("Tentang aplikasi ini...");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpageLayout = new javax.swing.GroupLayout(mainpage);
        mainpage.setLayout(mainpageLayout);
        mainpageLayout.setHorizontalGroup(
            mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpageLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpageLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainpageLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainpageLayout.createSequentialGroup()
                        .addGroup(mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                            .addGroup(mainpageLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAccount)))
                        .addGap(70, 70, 70))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(19, 19, 19))
        );
        mainpageLayout.setVerticalGroup(
            mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpageLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAccount))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(14, 14, 14))
        );

        getContentPane().add(mainpage, "mainpage");

        datasewaan.setBackground(new java.awt.Color(255, 255, 255));
        datasewaan.setPreferredSize(new java.awt.Dimension(650, 448));
        datasewaan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                datasewaanComponentShown(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Data Sewaan");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 8, 8));

        sewaTambah.setBackground(new java.awt.Color(0, 102, 204));
        sewaTambah.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        sewaTambah.setForeground(new java.awt.Color(255, 255, 255));
        sewaTambah.setText("Sewaan baru");
        sewaTambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        sewaTambah.setBorderPainted(false);
        sewaTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sewaTambah.setFocusPainted(false);
        sewaTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sewaTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sewaTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sewaTambahMouseExited(evt);
            }
        });
        sewaTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaTambahActionPerformed(evt);
            }
        });
        jPanel5.add(sewaTambah);
        jPanel5.add(filler1);

        bayarBtn.setBackground(new java.awt.Color(0, 153, 102));
        bayarBtn.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        bayarBtn.setForeground(new java.awt.Color(255, 255, 255));
        bayarBtn.setText("Bayar...");
        bayarBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        bayarBtn.setBorderPainted(false);
        bayarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bayarBtn.setFocusPainted(false);
        bayarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bayarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bayarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bayarBtnMouseExited(evt);
            }
        });
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });
        jPanel5.add(bayarBtn);

        sewaEdit.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        sewaEdit.setText("Edit");
        sewaEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        sewaEdit.setContentAreaFilled(false);
        sewaEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sewaEdit.setFocusPainted(false);
        sewaEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sewaEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sewaEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sewaEditMouseExited(evt);
            }
        });
        sewaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaEditActionPerformed(evt);
            }
        });
        jPanel5.add(sewaEdit);

        sewaHapus.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        sewaHapus.setForeground(new java.awt.Color(204, 0, 0));
        sewaHapus.setText("Hapus");
        sewaHapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        sewaHapus.setContentAreaFilled(false);
        sewaHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sewaHapus.setFocusPainted(false);
        sewaHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sewaHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sewaHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sewaHapusMouseExited(evt);
            }
        });
        sewaHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaHapusActionPerformed(evt);
            }
        });
        jPanel5.add(sewaHapus);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);

        tabelSewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a", "b", "c", "d"},
                {"e", "f", "g", "h"},
                {"i", "j", "k", null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSewaan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelSewaan.setGridColor(new java.awt.Color(204, 204, 204));
        tabelSewaan.setRowHeight(22);
        tabelSewaan.setShowGrid(true);
        tabelSewaan.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tabelSewaan);

        searchSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSewaActionPerformed(evt);
            }
        });
        searchSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchSewaKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel11.setText("Cari:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sovana/sewa/images/baseline_arrow_back_black_24dp.png"))); // NOI18N
        jButton1.setToolTipText("Kembali ke menu utama");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datasewaanLayout = new javax.swing.GroupLayout(datasewaan);
        datasewaan.setLayout(datasewaanLayout);
        datasewaanLayout.setHorizontalGroup(
            datasewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datasewaanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(datasewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(datasewaanLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datasewaanLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        datasewaanLayout.setVerticalGroup(
            datasewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datasewaanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(datasewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datasewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(searchSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(datasewaan, "datasewaan");

        databarang.setBackground(new java.awt.Color(255, 255, 255));
        databarang.setPreferredSize(new java.awt.Dimension(623, 449));
        databarang.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                databarangComponentShown(evt);
            }
        });

        searchBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarangActionPerformed(evt);
            }
        });
        searchBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarangKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setText("Data Barang");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setText("Cari:");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 8, 8));

        barangTambah.setBackground(new java.awt.Color(255, 102, 0));
        barangTambah.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        barangTambah.setForeground(new java.awt.Color(255, 255, 255));
        barangTambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        barangTambah.setBorderPainted(false);
        barangTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barangTambah.setFocusPainted(false);
        barangTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barangTambah.setLabel("Tambah barang");
        barangTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barangTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barangTambahMouseExited(evt);
            }
        });
        barangTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangTambahActionPerformed(evt);
            }
        });
        jPanel6.add(barangTambah);
        jPanel6.add(filler2);

        barangEdit.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        barangEdit.setText("Edit");
        barangEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        barangEdit.setContentAreaFilled(false);
        barangEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barangEdit.setFocusPainted(false);
        barangEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barangEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barangEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barangEditMouseExited(evt);
            }
        });
        barangEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangEditActionPerformed(evt);
            }
        });
        jPanel6.add(barangEdit);

        barangHapus.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        barangHapus.setForeground(new java.awt.Color(204, 0, 0));
        barangHapus.setText("Hapus");
        barangHapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        barangHapus.setContentAreaFilled(false);
        barangHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barangHapus.setFocusPainted(false);
        barangHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barangHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barangHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barangHapusMouseExited(evt);
            }
        });
        barangHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangHapusActionPerformed(evt);
            }
        });
        jPanel6.add(barangHapus);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sovana/sewa/images/baseline_arrow_back_black_24dp.png"))); // NOI18N
        jButton2.setToolTipText("Kembali ke menu utama");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setAutoscrolls(true);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a", "b", "c", "d"},
                {"e", "f", "g", "h"},
                {"i", "j", "k", null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.setGridColor(new java.awt.Color(204, 204, 204));
        tabelBarang.setRowHeight(22);
        tabelBarang.setShowGrid(true);
        tabelBarang.setShowHorizontalLines(false);
        jScrollPane2.setViewportView(tabelBarang);

        javax.swing.GroupLayout databarangLayout = new javax.swing.GroupLayout(databarang);
        databarang.setLayout(databarangLayout);
        databarangLayout.setHorizontalGroup(
            databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(databarangLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, databarangLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        databarangLayout.setVerticalGroup(
            databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databarangLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(databarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(searchBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(40, 40, 40)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(databarang, "databarang");

        riwayat.setBackground(new java.awt.Color(255, 255, 255));
        riwayat.setPreferredSize(new java.awt.Dimension(661, 436));
        riwayat.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                riwayatComponentShown(evt);
            }
        });

        searchRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRiwayatActionPerformed(evt);
            }
        });
        searchRiwayat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchRiwayatKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setText("Riwayat transaksi");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setText("Cari:");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 8, 8));

        riwayatCetak.setBackground(new java.awt.Color(0, 153, 255));
        riwayatCetak.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        riwayatCetak.setForeground(new java.awt.Color(255, 255, 255));
        riwayatCetak.setText("Cetak...");
        riwayatCetak.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        riwayatCetak.setBorderPainted(false);
        riwayatCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayatCetak.setFocusPainted(false);
        riwayatCetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        riwayatCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatCetakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatCetakMouseExited(evt);
            }
        });
        riwayatCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatCetakActionPerformed(evt);
            }
        });
        jPanel7.add(riwayatCetak);

        riwayatHapus.setBackground(new java.awt.Color(204, 204, 204));
        riwayatHapus.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        riwayatHapus.setForeground(new java.awt.Color(255, 51, 51));
        riwayatHapus.setText("Hapus");
        riwayatHapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        riwayatHapus.setContentAreaFilled(false);
        riwayatHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayatHapus.setFocusPainted(false);
        riwayatHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        riwayatHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatHapusMouseExited(evt);
            }
        });
        riwayatHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatHapusActionPerformed(evt);
            }
        });
        jPanel7.add(riwayatHapus);

        riwayatHapusAll.setBackground(new java.awt.Color(204, 204, 204));
        riwayatHapusAll.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        riwayatHapusAll.setForeground(new java.awt.Color(204, 0, 0));
        riwayatHapusAll.setText("Hapus semua");
        riwayatHapusAll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        riwayatHapusAll.setContentAreaFilled(false);
        riwayatHapusAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riwayatHapusAll.setFocusPainted(false);
        riwayatHapusAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        riwayatHapusAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatHapusAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatHapusAllMouseExited(evt);
            }
        });
        riwayatHapusAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatHapusAllActionPerformed(evt);
            }
        });
        jPanel7.add(riwayatHapusAll);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sovana/sewa/images/baseline_arrow_back_black_24dp.png"))); // NOI18N
        jButton3.setToolTipText("Kembali ke menu utama");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setAutoscrolls(true);

        tabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a", "b", "c", "d"},
                {"e", "f", "g", "h"},
                {"i", "j", "k", null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelRiwayat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelRiwayat.setGridColor(new java.awt.Color(204, 204, 204));
        tabelRiwayat.setRowHeight(22);
        tabelRiwayat.setShowGrid(true);
        tabelRiwayat.setShowHorizontalLines(false);
        jScrollPane3.setViewportView(tabelRiwayat);

        belumLunasCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        belumLunasCheckbox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        belumLunasCheckbox.setText("Tampilkan yang belum lunas");
        belumLunasCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belumLunasCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout riwayatLayout = new javax.swing.GroupLayout(riwayat);
        riwayat.setLayout(riwayatLayout);
        riwayatLayout.setHorizontalGroup(
            riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, riwayatLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(riwayatLayout.createSequentialGroup()
                        .addComponent(belumLunasCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        riwayatLayout.setVerticalGroup(
            riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(searchRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(31, 31, 31)
                .addGroup(riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(belumLunasCheckbox))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(riwayat, "riwayat");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void goToPage(String page) {
        CardLayout cl = (CardLayout) (getContentPane().getLayout());
        cl.show(getContentPane(), page);
    }

    public void deleteSelectedRow() {
        try {
            String sql = "delete from sewaan where id = " + tabelSewaan.getValueAt(tabelSewaan.getSelectedRow(), 0);
            Connection conn = (Connection) Connect.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.execute();
            conn.prepareStatement("ALTER TABLE sewaan DROP id").execute();
            conn.prepareStatement("ALTER TABLE sewaan ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST").execute();
            load_table_sewaan();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }

    public void showSummaryCount() {
        numberBarang.setText("...");
        numberSewa.setText("...");
        numberBlmLunas.setText("...");
        java.awt.EventQueue.invokeLater(() -> {
            try {
                Connection conn = (Connection) Connect.configDB();
                java.sql.Statement stm = conn.createStatement();
                ResultSet countSewa = stm.executeQuery("select count(id) from sewaan");
                while (countSewa.next()) {
                    numberSewa.setText(countSewa.getString(1));
                }
                ResultSet countBarang = stm.executeQuery("select count(id) from barang");
                while (countBarang.next()) {
                    numberBarang.setText(countBarang.getString(1));
                }
                ResultSet countBlmLunas = stm.executeQuery("select count(id) from pembayaran where sisa like '-%'");
                while (countBlmLunas.next()) {
                    numberBlmLunas.setText(countBlmLunas.getString(1));
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
            }
        });
    }

    public void load_table_sewaan() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Tanggal sewa");
        model.addColumn("Nama penyewa");
        model.addColumn("Barang sewaan");
        model.addColumn("Jumlah");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        //menampilkan data database kedalam tabel
        try {
            String sql;
            if (!searchSewa.getText().isEmpty()) {
                sql = "select * from sewaan where tanggal like '%" + searchSewa.getText() + "%'"
                        + "or nama like '%" + searchSewa.getText() + "%' "
                        + "or barang_sewaan like '%" + searchSewa.getText() + "%' "
                        + "or jumlah like '%" + searchSewa.getText() + "%' "
                        + "or alamat like '%" + searchSewa.getText() + "%' "
                        + "or telp like '%" + searchSewa.getText() + "%'";
            } else {
                sql = "select*from sewaan";
            }
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString(1),
                    formatter.format(res.getDate(2)),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7)});
            }
            tabelSewaan.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }

    public void load_table_barang() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Nama barang");
        model.addColumn("Harga");
        model.addColumn("Ketersediaan");
        //menampilkan data database kedalam tabel
        try {
            String sql;
            if (!searchBarang.getText().isEmpty()) {
                sql = "select * from barang where id like '%" + searchBarang.getText() + "%'"
                        + "or nama_barang like '%" + searchBarang.getText() + "%' "
                        + "or harga like '%" + searchBarang.getText() + "%' "
                        + "or status like '%" + searchBarang.getText() + "%'";
            } else {
                sql = "select*from barang";
            }
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4)
                });
            }
            tabelBarang.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }

    public void load_table_riwayat() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Tgl sewa");
        model.addColumn("Tgl Kembali");
        model.addColumn("Nama penyewa");
        model.addColumn("Barang sewaan");
        model.addColumn("Jumlah");
        model.addColumn("Harga satuan");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        model.addColumn("Total biaya");
        model.addColumn("Jumlah bayar");
        model.addColumn("Kembalian/Kurang");
        //menampilkan data database kedalam tabel
        try {
            String sql;
            if (!"".equals(searchRiwayat.getText()) && searchRiwayat.isFocusOwner()) {
                sql = "select * from pembayaran where tgl_sewa like '%" + searchRiwayat.getText() + "%'"
                        + "or tgl_kembali like '%" + searchRiwayat.getText() + "%' "
                        + "or nama_penyewa like '%" + searchRiwayat.getText() + "%' "
                        + "or barang_sewaan like '%" + searchRiwayat.getText() + "%' "
                        + "or jumlah like '%" + searchRiwayat.getText() + "%' "
                        + "or harga_satuan like '%" + searchRiwayat.getText() + "%' "
                        + "or alamat like '%" + searchRiwayat.getText() + "%' "
                        + "or telp like '%" + searchRiwayat.getText() + "%' "
                        + "or total_biaya like '%" + searchRiwayat.getText() + "%' "
                        + "or jumlah_bayar like '%" + searchRiwayat.getText() + "%' "
                        + "or sisa like '%" + searchRiwayat.getText() + "%'";
            } else {
                if (belumLunasCheckbox.isSelected()) {
                    sql = "select * from pembayaran where sisa like '-%'";
                } else {
                    sql = "select * from pembayaran";
                }

            }
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString(1),
                    formatter.format(res.getDate(2)),
                    formatter.format(res.getDate(3)),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),
                    res.getString(7),
                    res.getString(8),
                    res.getString(9),
                    res.getString(10),
                    res.getString(11),
                    res.getString(12)
                });
            }
            tabelRiwayat.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }

    private void btnToSewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToSewaanActionPerformed
        goToPage("datasewaan");
    }//GEN-LAST:event_btnToSewaanActionPerformed

    private void btnToBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToBarangActionPerformed
        goToPage("databarang");
    }//GEN-LAST:event_btnToBarangActionPerformed

    private void btnToPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToPaymentActionPerformed
        goToPage("riwayat");
    }//GEN-LAST:event_btnToPaymentActionPerformed

    private void sewaTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sewaTambahMouseEntered
        sewaTambah.setBackground(new Color(0, 130, 224));
    }//GEN-LAST:event_sewaTambahMouseEntered

    private void sewaTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sewaTambahMouseExited
        sewaTambah.setBackground(new Color(0, 102, 204));
    }//GEN-LAST:event_sewaTambahMouseExited

    private void sewaEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sewaEditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaEditMouseEntered

    private void sewaEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sewaEditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaEditMouseExited

    private void sewaHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sewaHapusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaHapusMouseEntered

    private void sewaHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sewaHapusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaHapusMouseExited

    private void sewaHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaHapusActionPerformed
        try {
            String sql = "delete from sewaan where id = " + tabelSewaan.getValueAt(tabelSewaan.getSelectedRow(), 0);
            Connection conn = (Connection) Connect.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            Object[] tombol = {"Hapus", "Batal"};
            int yatidak = JOptionPane.showOptionDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi hapus",
                    0, 2, null, tombol, tombol[1]);
            if (yatidak == JOptionPane.NO_OPTION) {
                this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            } else if (yatidak == JOptionPane.YES_OPTION) {
                ps.execute();
                conn.prepareStatement("ALTER TABLE sewaan DROP id").execute();
                conn.prepareStatement("ALTER TABLE sewaan ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST").execute();
                load_table_sewaan();
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data:\n" + e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_sewaHapusActionPerformed

    private void searchSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSewaActionPerformed

    private void bayarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarBtnMouseEntered

    private void bayarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarBtnMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        goToPage("mainpage");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAccountMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseReleased

    }//GEN-LAST:event_btnAccountMouseReleased

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        useroptions.show(this, btnAccount.getX(), btnAccount.getY() + btnAccount.getHeight() * 2);
    }//GEN-LAST:event_btnAccountActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        dispose();
        new com.sovana.sewa.loginactivity.loginDialog().setVisible(true);

    }//GEN-LAST:event_menuLogoutActionPerformed

    private void sewaTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaTambahActionPerformed
        tambahSewaDialog dialog = new tambahSewaDialog(this, true);
        dialog.addMode();
        dialog.lastIdSewaan();
        dialog.setVisible(true);
    }//GEN-LAST:event_sewaTambahActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tambahSewaDialog dialog = new tambahSewaDialog(this, true);
        dialog.addMode();
        dialog.lastIdSewaan();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void datasewaanComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_datasewaanComponentShown
        load_table_sewaan();
    }//GEN-LAST:event_datasewaanComponentShown

    private void sewaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaEditActionPerformed
        try {
            tambahSewaDialog dialog = new tambahSewaDialog(this, true);
            dialog.editMode(tabelSewaan.getValueAt(tabelSewaan.getSelectedRow(), 0).toString());
            dialog.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        }
    }//GEN-LAST:event_sewaEditActionPerformed

    private void searchSewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchSewaKeyReleased
        load_table_sewaan();
    }//GEN-LAST:event_searchSewaKeyReleased

    private void searchBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarangActionPerformed

    private void searchBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarangKeyReleased
        load_table_barang();
    }//GEN-LAST:event_searchBarangKeyReleased

    private void barangTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangTambahMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_barangTambahMouseEntered

    private void barangTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangTambahMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_barangTambahMouseExited

    private void barangTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangTambahActionPerformed
        tambahBarangDialog dialog = new tambahBarangDialog(this, true);
        dialog.addMode();
        dialog.lastIdBarang();
        dialog.setVisible(true);
    }//GEN-LAST:event_barangTambahActionPerformed

    private void barangEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangEditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_barangEditMouseEntered

    private void barangEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangEditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_barangEditMouseExited

    private void barangEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangEditActionPerformed
        try {
            tambahBarangDialog dialog = new tambahBarangDialog(this, true);
            dialog.editMode(tabelBarang.getValueAt(tabelBarang.getSelectedRow(), 0).toString());
            dialog.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        }

    }//GEN-LAST:event_barangEditActionPerformed

    private void barangHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangHapusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_barangHapusMouseEntered

    private void barangHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangHapusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_barangHapusMouseExited

    private void barangHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangHapusActionPerformed
        try {
            String sql = "delete from barang where id = " + tabelBarang.getValueAt(tabelBarang.getSelectedRow(), 0);
            Connection conn = (Connection) Connect.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            Object[] tombol = {"Hapus", "Batal"};
            int yatidak = JOptionPane.showOptionDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi hapus",
                    0, 2, null, tombol, tombol[1]);
            if (yatidak == JOptionPane.NO_OPTION) {
                this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            } else if (yatidak == JOptionPane.YES_OPTION) {
                ps.execute();
                conn.prepareStatement("ALTER TABLE barang DROP id").execute();
                conn.prepareStatement("ALTER TABLE barang ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST").execute();
                load_table_barang();
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data:\n" + e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_barangHapusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        goToPage("mainpage");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void databarangComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_databarangComponentShown
        load_table_barang();
    }//GEN-LAST:event_databarangComponentShown

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        java.awt.EventQueue.invokeLater(() -> {
            try {
                bayarDialog dialog = new bayarDialog(this, true);
                dialog.fillFormSewaan(tabelSewaan.getValueAt(tabelSewaan.getSelectedRow(), 0).toString());
                dialog.setVisible(true);
            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
            }
        });
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_bayarBtnActionPerformed

    private void searchRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchRiwayatActionPerformed

    private void searchRiwayatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchRiwayatKeyReleased
        load_table_riwayat();
    }//GEN-LAST:event_searchRiwayatKeyReleased

    private void riwayatHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatHapusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatHapusMouseEntered

    private void riwayatHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatHapusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatHapusMouseExited

    private void riwayatHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatHapusActionPerformed
        try {
            String sql = "delete from pembayaran where id = " + tabelRiwayat.getValueAt(tabelRiwayat.getSelectedRow(), 0);
            Connection conn = (Connection) Connect.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            Object[] tombol = {"Hapus", "Batal"};
            int yatidak = JOptionPane.showOptionDialog(null, "Anda yakin ingin menghapus riwayat ini?", "Konfirmasi hapus",
                    0, 2, null, tombol, tombol[1]);
            if (yatidak == JOptionPane.NO_OPTION) {
                this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            } else if (yatidak == JOptionPane.YES_OPTION) {
                ps.execute();
                conn.prepareStatement("ALTER TABLE pembayaran DROP id").execute();
                conn.prepareStatement("ALTER TABLE pembayaran ADD id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST").execute();
                load_table_riwayat();
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data:\n" + e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_riwayatHapusActionPerformed

    private void riwayatHapusAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatHapusAllMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatHapusAllMouseEntered

    private void riwayatHapusAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatHapusAllMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatHapusAllMouseExited

    private void riwayatHapusAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatHapusAllActionPerformed
        try {
            String sql = "truncate table pembayaran";
            Connection conn = (Connection) Connect.configDB();
            PreparedStatement ps = conn.prepareStatement(sql);
            Object[] tombol = {"Hapus", "Batal"};
            int yatidak = JOptionPane.showOptionDialog(null, "SEMUA riwayat pembayaran akan dihapus.\nLanjutkan?", "Konfirmasi hapus",
                    0, 2, null, tombol, tombol[1]);
            if (yatidak == JOptionPane.NO_OPTION) {
                setDefaultCloseOperation(EXIT_ON_CLOSE);
            } else if (yatidak == JOptionPane.YES_OPTION) {
                ps.execute();
                load_table_riwayat();
            }

        } catch (ArrayIndexOutOfBoundsException | HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data:\n" + e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_riwayatHapusAllActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        goToPage("mainpage");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void riwayatComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_riwayatComponentShown
        load_table_riwayat();
    }//GEN-LAST:event_riwayatComponentShown

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tambahBarangDialog dialog = new tambahBarangDialog(this, true);
        dialog.addMode();
        dialog.lastIdBarang();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void menuEditAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditAccActionPerformed
        new changePasswordDialog(this, true).setVisible(true);
    }//GEN-LAST:event_menuEditAccActionPerformed

    private void mainpageComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mainpageComponentShown
        showSummaryCount();
    }//GEN-LAST:event_mainpageComponentShown

    private void belumLunasCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belumLunasCheckboxActionPerformed
        load_table_riwayat();
    }//GEN-LAST:event_belumLunasCheckboxActionPerformed

    private void riwayatCetakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatCetakMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatCetakMouseEntered

    private void riwayatCetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatCetakMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatCetakMouseExited

    private void riwayatCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatCetakActionPerformed
        try {
            printPreviewDialog pvd = new printPreviewDialog(this, true);
            int baris = tabelRiwayat.getSelectedRow();
            SimpleDateFormat clockformatter = new SimpleDateFormat("dd MMM yyyy hh:mm:ss");
            String dateNow = clockformatter.format(new Date());
            pvd.setLaporanText("\n\t------------------------------------------\n"
                    + String.format("\t%-15s\t%n", "SEWA TEROP H. NASHIR")
                    + String.format("\t%-15s\t%n", "Bukti Pembayaran")
                    + String.format("\t%s %-15s\t%n", "Tanggal", dateNow)
                    + "\t------------------------------------------\t\n"
                    + String.format("\t%-15s: %-15s%n", "Nama", tabelRiwayat.getValueAt(baris, 3))
                    + String.format("\t%-15s: %-15s%n", "Tgl sewa", tabelRiwayat.getValueAt(baris, 1))
                    + String.format("\t%-15s: %-15s%n", "Tgl kembali", tabelRiwayat.getValueAt(baris, 2))
                    + String.format("\t%-15s: %s buah %-15s%n", "Barang sewaan", tabelRiwayat.getValueAt(baris, 5), tabelRiwayat.getValueAt(baris, 4))
                    + String.format("\t%-15s: %-15s%n", "Alamat", tabelRiwayat.getValueAt(baris, 7))
                    + String.format("\t%-15s: %-15s%n", "Telp penyewa", tabelRiwayat.getValueAt(baris, 8))
                    + "\t------------------------------------------\n"
                    + String.format("\t%-18s: Rp%,d%-17s%n", "Harga satuan", Integer.valueOf((String) tabelRiwayat.getValueAt(baris, 6)), ",-")
                    + String.format("\t%-18s: Rp%,d%-17s%n", "Total biaya", Integer.valueOf((String) tabelRiwayat.getValueAt(baris, 9)), ",-")
                    + String.format("\t%-18s: Rp%,d%-17s%n", "Jumlah bayar", Integer.valueOf((String) tabelRiwayat.getValueAt(baris, 10)), ",-")
                    + String.format("\t%-18s: Rp%,d%-17s%n%n", "Kembalian/kurang*", Integer.valueOf((String) tabelRiwayat.getValueAt(baris, 11)), ",-")
                    + String.format("\t%-18s\t%n", "*Coret yang tidak perlu")
            );
            pvd.setVisible(true);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih satu data terlebih dahulu", "Error", 0);
        }
    }//GEN-LAST:event_riwayatCetakActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new com.sovana.sewa.dialogactivity.AboutDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangEdit;
    private javax.swing.JButton barangHapus;
    private javax.swing.JButton barangTambah;
    private javax.swing.JButton bayarBtn;
    private javax.swing.JCheckBox belumLunasCheckbox;
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnToBarang;
    private javax.swing.JButton btnToPayment;
    private javax.swing.JButton btnToSewaan;
    private javax.swing.JPanel databarang;
    private javax.swing.JPanel datasewaan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainpage;
    private javax.swing.JMenuItem menuEditAcc;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JLabel numberBarang;
    private javax.swing.JLabel numberBlmLunas;
    private javax.swing.JLabel numberSewa;
    private javax.swing.JPanel riwayat;
    private javax.swing.JButton riwayatCetak;
    private javax.swing.JButton riwayatHapus;
    private javax.swing.JButton riwayatHapusAll;
    private javax.swing.JTextField searchBarang;
    private javax.swing.JTextField searchRiwayat;
    private javax.swing.JTextField searchSewa;
    private javax.swing.JButton sewaEdit;
    private javax.swing.JButton sewaHapus;
    private javax.swing.JButton sewaTambah;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tabelRiwayat;
    private javax.swing.JTable tabelSewaan;
    private javax.swing.JPopupMenu useroptions;
    // End of variables declaration//GEN-END:variables
}
